
TEST_SERVICE_FILE_EXTENTION	= cpp
TEST_SERVICE_SRC_PATH     	= $(TEST_SERVICE_PATH)/source
TEST_SERVICE_RES_SRC_PATH	= $(TEST_SERVICE_PATH)/resource
TEST_SERVICE_INCLUDE_PATH 	= $(TEST_PUB_INCLUDE_PATH) $(SERVICE_INCLUDE_PATH)
TEST_SERVICE_OBJS_PATH    	= $(TEST_OBJS_PATH)/SERVICE
TEST_SERVICE_DEPS_PATH		= $(TEST_DEPS_PATH)/SERVICE
TEST_SERVICE_RES_BUILD_PATH	= $(TEST_RESS_PATH)/SERVICE
TEST_SERVICE_CFLAGS			= $(TEST_CODE_CFLAGS) -DRESOURCE_PATH=\"Resource/TEST/SERVICE/\"
TEST_SERVICE_DEPEND_CFLAGS	= $(TEST_DEPEND_CFLAGS)

TEST_SERVICE_INCLUDE = $(addprefix -I, $(TEST_SERVICE_INCLUDE_PATH))
TEST_SERVICE_SRCS	= $(wildcard $(TEST_SERVICE_SRC_PATH)/*.$(TEST_SERVICE_FILE_EXTENTION))
TEST_SERVICE_OBJS	= $(addprefix $(TEST_SERVICE_OBJS_PATH)/,$(notdir $(subst .$(TEST_SERVICE_FILE_EXTENTION),.o,$(TEST_SERVICE_SRCS))))
TEST_SERVICE_DEPS	= $(addprefix $(TEST_SERVICE_DEPS_PATH)/,$(notdir $(subst .$(TEST_SERVICE_FILE_EXTENTION),.d,$(TEST_SERVICE_SRCS))))
TEST_SERVICE_SRC_RES	= $(wildcard $(TEST_SERVICE_RES_SRC_PATH)/*)
TEST_SERVICE_RESS	= $(addprefix $(TEST_SERVICE_RES_BUILD_PATH)/,$(notdir $(TEST_SERVICE_SRC_RES)))
ALL_OBJS 	 += $(TEST_SERVICE_OBJS)
ALL_DEPS	 += $(TEST_SERVICE_DEPS)
ALL_RESS	 += $(TEST_SERVICE_RESS)

$(TEST_SERVICE_RES_BUILD_PATH)/% : $(TEST_SERVICE_RES_SRC_PATH)/%
	@$(MKDIR) $(TEST_SERVICE_RES_BUILD_PATH)
	@echo copy SERVICE resource:$(notdir $<)
	@$(COPY) $< $@
	@echo Done!

$(TEST_SERVICE_DEPS_PATH)/%.d : $(TEST_SERVICE_SRC_PATH)/%.$(TEST_SERVICE_FILE_EXTENTION)
	@$(MKDIR) $(TEST_SERVICE_DEPS_PATH)
	@echo Making $(notdir $@) ...
	@$(CC) $(TEST_SERVICE_DEPEND_CFLAGS) $(TEST_SERVICE_INCLUDE) $< | sed 's/$*.o:/$(subst /,\/,$(TEST_SERVICE_OBJS_PATH))\/$*.o:/g' > $@
	@echo Done!

-include $(TEST_SERVICE_DEPS)

$(TEST_SERVICE_OBJS_PATH)/%.o : $(TEST_SERVICE_SRC_PATH)/%.$(TEST_SERVICE_FILE_EXTENTION)
	@$(MKDIR) $(TEST_SERVICE_OBJS_PATH)
	@echo Making $(notdir $@) ...
	@$(CC) $(TEST_SERVICE_CFLAGS) $(TEST_SERVICE_INCLUDE) $< -c -o $@
	@echo Done!


